// Generated by CoffeeScript 1.4.0
var app = {}, restify, packageJson, package_parser, settings;

restify = require('restify');

package_parser = require('package-parser');

packageJson = package_parser.getPackageJsonSync();

settings = packageJson.coffeebone.settings;

app.server = restify.createServer();
app.server.use(restify.acceptParser(app.server.acceptable));
app.server.use(restify.authorizationParser());
app.server.use(restify.dateParser());
app.server.use(restify.queryParser());
app.server.use(restify.bodyParser());

app.mongoose = require('mongoose');

app.db = app.mongoose.createConnection(settings.mongo.host, settings.mongo.dbName);

app.getModel = function(name) {
  return app.db.model(name, app.schemas[name]);
};

app.db.once('open', function() {
  require('./schemas').initialize(app);
  require('./routes').initialize(app);
  return app.server.listen(settings.port, function() {
	console.log('%s listening at %s, love & peace', app.server.name, app.server.url);
  });
});
