// Generated by CoffeeScript 1.4.0

define(['./../collections/wordCollection'], function(WordCollection) {
  return Backbone.Model.extend({
    idAttribute: "_id",
    defaults: function(){
    	return {
	    	
	    	appname: 'bits',
	    	
 		};
    },

    initialize: function(){
    	this.words = new WordCollection();
    	this.words.fetch();//?
    }
  });
});
