// Generated by CoffeeScript 1.4.0

define(['backbone'], function(Backbone) {
  return Backbone.Model.extend({
    idAttribute: "_id",
    defaults: function(){
    	return {
	    	duration: 15,
            color: "rgba(40, 40, 40, .6)",
            done: false
 		};
    }
  });
});
