// Generated by CoffeeScript 1.4.0

exports.initialize = function(app) {
  return require("fs").readdirSync("./routes").forEach(function(file) {
    var route;
    if (!file.match(new RegExp("\.js$"))) {
      return;
    }
    if (file === 'index.js') {
      return;
    }
    route = require("./" + file);
    return route.initialize(app);
  });
};
