// Generated by CoffeeScript 1.4.0

var restify = require('restify');
var publicDir = require('package-parser').getPackageJsonSync().coffeebone.settings.publicDir;
exports.initialize = function(app) {
  app.server.pre(function(req, res, next){
    if(req.url == '/'){
      req.url = '/index.html' 
    }
    return next();
  });
  app.server.get('/\/.*/', restify.serveStatic({
    directory: publicDir
  }));
  return app.server.get('/coffeebone/configuration', function(req, res, next) {
    var conf, package_parser;
    package_parser = require('package-parser');
    conf = package_parser.getPackageJsonSync();
    if (conf.coffeebone && conf.coffeebone.frontend) {
      return res.send(JSON.stringify(conf.coffeebone.frontend));
    } else {
      return res.send('{}');
    }
  });
};
