// Generated by CoffeeScript 1.4.0
var path;

path = require('path');

exports.initialize = function(app) {
  return require("fs").readdirSync("./schemas").forEach(function(file) {
    var schemaInitializer;
    if (!file.match(new RegExp("\.js$"))) {
      return;
    }
    if (file === 'index.js') {
      return;
    }
    schemaInitializer = require("./" + file);
    if (typeof app['schemas'] === 'undefined') {
      app['schemas'] = {};
    }
    return app['schemas'][path.basename(file, '.js')] = schemaInitializer.initialize(app);
  });
};
